### PR TITLE
Cannot close file if one of the write operations fails

### LINKED ISSUE #2963: Cannot close file if one of the write operations fails
Version :  
Vert.x : 3.7.0
Vert.x - Web : 3.7.0

I test thing with vert.x and I discover that :
-> If file transfer start , create file & fill it.
-> If disk size becomes full.
-> BodyHandler does not trigger an Http response.
-> The guilty seems to be the wich call close on the file but because it remains byte to write, closed is defered & never called, callback never called. 
https://github.com/eclipse-vertx/vert.x/blob/ba47fac59a4b78ff858b3858e7971083a2edce97/src/main/java/io/vertx/core/http/impl/HttpServerFileUploadImpl.java#L166-L180

because close will defer to :
https://github.com/eclipse-vertx/vert.x/blob/645f6d4d41e0301155501b1e287ac49d6e60573b/src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java#L521-L531

and the because of writesOutstanding != 0 (some byte left because we cannot write the all things), close is defered and never called because the completion handler which is the only part who called the defered method is always in failure (no space on disk) : 
https://github.com/eclipse-vertx/vert.x/blob/645f6d4d41e0301155501b1e287ac49d6e60573b/src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java#L163-L189
 
Reproducer : 
I have create a tempory partition on an unbuntu desktop (sudo mount -t tmpfs -o size=90M tmpfs /media/testUpload/) and try to download a file greater that 90Mo.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #2963

### CODE REVIEW

File: src/test/java/io/vertx/core/file/FileSystemTest.java [hunk 1]
```diff
@@ -1133,6 +1127,24 @@ public void testWriteAsync() {
     await();
   }
 
+  @Test(timeout = 5000)
```
Comment (vietj) [inline src/test/java/io/vertx/core/file/FileSystemTest.java:1130]: Did you check this timeout in Travis ? it sounds low to me and prone to false negatives

Comment (tsegismont) [reply src/test/java/io/vertx/core/file/FileSystemTest.java:1130]: The build passed https://travis-ci.org/github/eclipse-vertx/vert.x/builds/687019097

Actually I added this timeout so that it failed fast while the bug was not fixed on my box. I will remove it

Comment (tsegismont) [reply src/test/java/io/vertx/core/file/FileSystemTest.java]: Done
