### PR TITLE
Ensure that the task is not in the tasks queue when it is rejected from the executor

### LINKED ISSUE #4900: TasksQueue doesn't remove entry from tasks on RejectedExecutionException
### Version

`master` branch.

### Context

I had a look at the code when analyzing a problem in the 4.4.x after I configured a thread pool with a limited backlog which would reject executions eventually.

I found that the code in `master` throws the exception that the task is rejected, but then the task is still in the `taskQueue`, so it will eventually be executed when another task is then successfully submitted.
So for the caller it is both rejected and accepted, which is confusing and IMHO wrong.

I'll create a different issue for that as it doesn't handle the RejectedExecutionException at all.

### Do you have a reproducer?

Here a unit test as a reproducer - not that (at least for the reproducer) I made the `tasks` attribute public to I can use it the test.  See https://github.com/ahus1/vert.x/tree/poc-show-how-taskqueue-fails-in-main

```
    TaskQueue taskQueue = new TaskQueue();
    Executor executorThatAlwaysThrowsRejectedExceptions = new Executor() {
        @Override
        public void execute(Runnable command) {
            throw new RejectedExecutionException();
        }
    };

    assertThatThrownBy(() -> {
        taskQueue.execute(new Thread(), executorThatAlwaysThrowsRejectedExceptions);
      }).isInstanceOf(RejectedExecutionException.class);

    // this fails in main
    Assertions.assertThat(taskQueue.tasks).isEmpty();
```

### Steps to reproduce

See test.

### Extra

I can start writing a test, but I'm not sure on how to test this.

### PR DESCRIPTION
**Pull request by ahus1**
Closes #4900

Motivation:

This is a PR to address #4900. It is rather crude, and uses package visibility. While this does the job to make the assertions, I'd be happy to receive advice on how to change it to match the Vert.x's project way.

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ahus1** [comment]
Updated the PR to ensure proper encapsulation in `TaskQueue` even for tests by adding an `isEmpty()` method.

**Comment by vietj** [comment]
can you elaborate when/how this happens ? if a task is rejected it usually means that vertx is closed, unless I am wrong ?

**Comment by ahus1** [comment]
For me, Vert.x is used as part of Quarkus, which is then the base of Keycloak. At the moment I'm running some load tests around Keycloak, and I want to have a first naive load shedding in place.

In a Keycloak setup, Quarkus replaces the executor pool of Vert.x with its own thread pool I can ask Quarkus to limit the backlog of the executor thread pool using a configuration `QUARKUS_THREAD_POOL_QUEUE_SIZE=100`. Once I do this, the thread doesn't allow for an unlimited queue size. If under high load the queue size is exceeded, the requests are rejected. 

I'm discussing more elaborate means of load shedding and not relying on the thread pool queue site. Until that is in place, this is all I have. 

I hope this adds the context the issue is missing.

**Comment by vietj** [comment]
thanks for the context

File: src/main/java/io/vertx/core/impl/TaskQueue.java [hunk 1]
```diff
@@ -125,19 +125,30 @@ public Consumer<Runnable> unschedule() {
    */
   public void execute(Runnable task, Executor executor) {
     synchronized (tasks) {
-      tasks.add(new ExecuteTask(task, executor));
+      ExecuteTask executeTask = new ExecuteTask(task, executor);
+      tasks.add(executeTask);
```
Comment (vietj) [inline src/main/java/io/vertx/core/impl/TaskQueue.java:129]: I think instead since we are in a synchronized block, we could move this addition to the bottom of the block after we are sure the executor accepted the task instead of adding/removing it

**Comment by ahus1** [comment]
@vietj - thank you for the review. I've moved the statement, and also added a comment to state why this is the right place. Please give it another review when you have the time.

**Comment by vietj** [comment]
thanks for the contribution, do you mind porting this to the 4.x branch ?

**Comment by ahus1** [comment]
@vietj - thank you for reviewing and merging this PR. Here's the backport for this change to 4.x: #4904
