### PR TITLE
Use fast thread local and fix GC nepotism (Fixes #4749) (#4750)

### LINKED ISSUE #4749: ThreadLocal::remove performance impacts
https://github.com/eclipse-vertx/vert.x/blob/04d4d65fb47a3db4cd8a320795a397f1ae678173/src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java#L60 introduced to solve https://github.com/eclipse-vertx/vert.x/issues/4583 is not performant (for our use cases), see
https://github.com/smallrye/smallrye-context-propagation/issues/424#issuecomment-1600718621

A different mechanism or just using `FastThreadLocal`'s (to ve verified if they have the same impact) would solve it.

### PR DESCRIPTION
**Pull request by franz1981**
* Use fast thread local and fix GC nepotism (Fixes #4749)
* Replace order of reentrant task's merge

### CODE REVIEW

File: src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java [hunk 1]
```diff
@@ -27,7 +28,12 @@ public class CombinerExecutor<S> implements Executor<S> {
   private final Queue<Action<S>> q = PlatformDependent.newMpscQueue();
   private final AtomicInteger s = new AtomicInteger();
   private final S state;
-  private final ThreadLocal<Task> current = new ThreadLocal<>();
+
+  protected final class InProgressTail {
```
Comment (He-Pin) [inline src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:32]: Can it be `static`?

Comment (franz1981) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:32]: Uh!! Missed that you are right! Please open a pr, we love PRs

Comment (franz1981) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:32]: And many thanks to lookin at it!

File: src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java [hunk 2]
```diff
@@ -40,50 +46,46 @@ public void submit(Action<S> action) {
...
+        Task task = a.execute(state);
+        if (task != null) {
+          if (head == null) {
+            assert tail == null;
+            tail = task;
+            head = task;
+          } else {
+            tail = tail.next(task);
+          }
+        }
```
Comment (He-Pin) [inline src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:65]: The old `pollAndExecute` seems will poll and execute all actions and it will only execute one now, is that expected?

File: src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java (hunk 1 above)
Comment (He-Pin) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:32]: Glad that help, I'm using Vertx at work too, very great project!

File: src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java (hunk 2 above)
Comment (franz1981) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:65]: Good catch, I have cherry picked this from and old branch of mine and probably dropped the for, are you ok sending a pr to fix what you have found?

**Comment by franz1981** [comment]
@He-Pin sent some new commit, please check ;)

File: src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java (hunk 2 above)
Comment (He-Pin) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:67]: But you already have this pr, I think you can address it in this pr too♡(*´∀｀*)人(*´∀｀*)♡

Comment (franz1981) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:67]: Already done, we have another one already merged for master too

Comment (He-Pin) [reply src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java:67]: i see, i can try a pr tomorrow then.
